version: "3.9"
services:
  langbro_backend:
    build:
      dockerfile: ci/docker/backend.Dockerfile
      context: ../../
    ports:
      - "8080:8080"
    container_name: langbro_backend
    restart: unless-stopped

  langbro_mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ../scripts/mongodb_init.sh:/docker-entrypoint-initdb.d/mongodb_init.sh
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({serverStatus:1}).ok'",
          "|",
          "mongo admin",
          "-u $MONGO_INITDB_ROOT_USERNAME",
          "-p $MONGO_INITDB_ROOT_PASSWORD",
          "--quiet | grep 1",
        ]
      interval: 1s
      timeout: 10s
      retries: 3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_USER=$MONGO_USER
      - MONGO_USER_PASSWORD=$MONGO_USER_PASSWORD
      - MONGO_USER_ROLE=$MONGO_USER_ROLE
    container_name: langbro_mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  default:
    name: langbro_net
