version: "3.9"
services:
  langbro_backend:
    build:
      dockerfile: ci/docker/backend.Dockerfile
      context: ../../
    ports:
      - "8080:8080"
    container_name: langbro_backend
    restart: unless-stopped

networks:
  default:
    name: langbro_net
